# Horcrux BUILD file for hello example
# This is a simple cc_binary target that demonstrates basic build functionality

cc_binary(
    name = "hello",
    srcs = ["main.cpp"],
    visibility = ["//visibility:public"],
)
# Horcrux BUILD file for hello example
# This is a simple cc_binary target that demonstrates basic build functionality

cc_binary(
    name = "hello",
    srcs = ["main.cpp"],
    visibility = ["//visibility:public"],
)
