# Horcrux BUILD file for libraries/network module

android_library(
    name = "network",
    srcs = glob([
        "src/main/java/**/*.java",
    ]),
    deps = [
        "@maven//:androidx_core_core_ktx",
    ],
    visibility = ["//visibility:public"],
)
